### ISSUE TITLE
Max number of base pals stuck

### ISSUE THREAD

**Issue by Anditooo** [legoduded/palworld-worldoptions#12]
My max number of pals in my base is stuck at 15 even when I change ini and download this file

**Comment by legoduded** [comment]
If you're using the web interface:
Import your PalWorldSettings.ini.
Make sure BaseCampWorkerMaxNum=20
Generate WorldOption.sav
Copy the file into `\Pal\Saved\SaveGames\0\<random>`
Start your server

If your base is over level 15, you should be able to add more pals.
If you're still having trouble, post your PalWorldSettings.ini

**Comment by Anditooo** [comment]
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.500000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=1,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=False,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=20,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=1.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword=""

I cut off all the extra ID stuff at the end

**Comment by Anditooo** [comment]
It worked for a a bit then just quit working and now it wont get back to working

**Comment by legoduded** [comment]
Seems to be working for me. Try importing your settings on the web tool and generating another WorldOption.sav. Then copy it into your save folder.

Stop the server
Copy WorldOption.sav the file to:
 <Dedicated Server>\Pal\Saved\SaveGames\0\<random>\
(This path should also contain level.sav and levelmeta.sav)
Start your server

If your base is over level 15 you should be able to add more pals

**Comment by Anditooo** [comment]
i tried that and even tried the mod link and none of it worked

**Comment by Anditooo** [comment]
is it because it is a dedicated server? i rent it through game team

**Comment by Anditooo** [comment]
By the way it has to be the original file you download, it cant have (1),(2),etc. in it. When I deleted the old files of me trying it worked fine

**Comment by vqoley** [comment]
> By the way it has to be the original file you download, it cant have (1),(2),etc. in it. When I deleted the old files of me trying it worked fine

how did you do that? mine still not working. i using dedicated server on my pc (windows)

**Comment by legoduded** [comment]
> By the way it has to be the original file you download, it cant have (1),(2),etc. in it. When I deleted the old files of me trying it worked fine

Glad you got it working 👍
