### ISSUE TITLE
Don't know how to settings via website

### ISSUE THREAD

**Issue by MarryJ666** [legoduded/palworld-worldoptions#13]
hello legoduded and thanks for making this setting which everyone says to be working.
i don't know about coding and me and my friends want to have 20 pals at base. The problem is i don't know how i fill the bottom section of your setting on website.
i don't know which one to fill for PublicPort, PublicIP, RCONEnabled, Region, bUseAuth and BanListURL.

Can you help me with this?
thanks again for making this

**Comment by legoduded** [comment]
Hey, here is a page with some more info on these settings: https://help.dathost.net/article/150-palworld-how-to-edit-server-settings

PublicPort: Sets the public port for the Palworld server. (most cases leave this as default 8211)
PublicIP: Sets the public IP address for the Palworld server (can be left blank in most cases)
RCONEnabled: Enables or disables Remote Console (RCON) for server administration. (probably leave false if you're unsure)
Region: Sets the region for the Palworld server. (can be left blank)
bUseAuth Enables or disables server authentication.(I recommend leaving this true)
BanListURL: Sets the URL for the server's ban list. (can be left as default)
