### ISSUE TITLE
Blue after settings change

### ISSUE THREAD

**Issue by NovaSki11z** [legoduded/palworld-worldoptions#16]
I modified max base workers to 20 and it loads in and works but there is a very high amount of blue it puts lowing the fps of the server.

**Comment by legoduded** [comment]
Increasing the pals in the base will cause more stress on the server possibly lowering the FPS. Unfortunately, there is nothing I can do about that.

Some people have had success by changing the server tick rate
https://www.reddit.com/r/Palworld/comments/19avqax/comment/kip5w5w/?utm_source=share&utm_medium=web2x&context=3

also make sure you are running your server with arguments: -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
https://tech.palworldgame.com/settings-and-operation/arguments
