### ISSUE TITLE
bsecampmod worked perfectly on my linux server

### ISSUE THREAD

**Issue by ceramicwhite** [legoduded/palworld-worldoptions#17]
Thanks for that addition exactly what I needed.

if the table for increasing base radius is known/found, adding that as an addition would be amazing.

**Comment by Anditooo** [comment]
how did you get yours to work? i am trying to implement on my dedicated server and I cant get it to work?

**Comment by ceramicwhite** [comment]
drop it in your server files like so:
```
├── Pal
│   ├── Content
│   │   └── Paks
│   │       ├── 25LegendSchem_p.pak   <-- schematic drop buffed
│   │       ├── basecampmod_P.pak
│   │       ├── BetterVendors_P.pak   <-- Wandering Merchant sells more items
│   │       ├── BetterVixyFarming_P.pak   <-- Vixy has chance to dig up some slightly better items at ranch
│   │       ├── Buffed Hats_P.pak  <-- Cosmetic hats have stats matching metal helm
│   │       ├── CheapPalUpgradeReset_P.pak  <-- Cheaper pal reset 
│   │       ├── OreCrusher_P.pak  <-- Crushed can make ore. 1 = 50 stone
│   │       ├── Pal-LinuxServer.pak
│   │       ├── Realistics_Work_Suitability_LV4_P.pak   <--  Human slaves actually useful workers. Kinda OP
│   │       ├── William_PalShopMerchant_P.pak  <-- Pal Merchant sells more pals
│   │       └── WorkSpeedFood100_P.pak  <-- Eating lettuce buffs workers speed
```
Here's all the paks listed above, all are working on my linux server:
[Paks.zip](https://github.com/legoduded/palworld-worldoptions/files/14174819/Paks.zip)

basecampmod_P.pak I have set to max 100 at level 20 so make sure to set that in WorldOptions if you use it.

Edit: also btw I used the website to generate `basecampmod_P.pak`: https://palworldoptions.com/basecampmod/

**Comment by Anditooo** [comment]
![image](https://github.com/legoduded/palworld-worldoptions/assets/158647107/7fb4decc-c3fc-4ba7-850d-00832c8aa840)

**Comment by legoduded** [comment]
Glad it's working for you. :)

I haven't seen any server mods for increasing the base size yet but I'll look into it.
I only did the basecamp mod since I couldn't find one that had customized values.
