### ISSUE TITLE
No matter what port I use if it is not 8211 its ignored.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [legoduded/palworld-worldoptions#18]
I have reported this to devs but it seems like nothing can change default port.

**Comment by P3rf3ctXZer0** [comment]
![opera_4ynGdkTk7c 1](https://github.com/legoduded/palworld-worldoptions/assets/10351221/d99977da-52d5-4881-9c23-8c6cc8e9668f)

**Comment by P3rf3ctXZer0** [comment]
![AnyDesk_eye5yi05U8 1](https://github.com/legoduded/palworld-worldoptions/assets/10351221/1067c84c-cf54-4d31-bb36-cf47678a8886)

**Comment by Leayal** [comment]
@P3rf3ctXZer0 
According to [Palworld Docs](https://tech.palworldgame.com/dedicated-server-guide#settings).
You can try setting launch argument `-port=<number>`. For instance, `-port=7777` should make the server use UDP port 7777.

**Comment by legoduded** [comment]
as @Leayal mentioned the -port launch argument should work. I believe the publicport value in the ini might be for the public port others should use to connect to your server when you're in the community server list. But I'm also just guessing

**Comment by Leayal** [comment]
> as @Leayal mentioned the -port launch argument should work. I believe the publicport value in the ini might be for the public port others should use to connect to your server when you're in the community server list. But I'm also just guessing

My guess is the same, I think the values in the configuration is used to advertise server's address so that the in-game server browser can list your server properly.

P/s: I think this is regarding to some specific setups that a server uses different numbers for `public port` and `private port` (or `internal port`) in NAT configuration (or port forwarding configuration), which then you can make server bind to the private port number, while setting the .ini configuration to report your server should be connected via a different port number of the public IP.

**Comment by P3rf3ctXZer0** [comment]
> @P3rf3ctXZer0 According to [Palworld Docs](https://tech.palworldgame.com/dedicated-server-guide#settings). You can try setting launch argument `-port=<number>`. For instance, `-port=7777` should make the server use UDP port 7777.

This is the first thing I tried.

**Comment by Leayal** [comment]
> This is the first thing I tried.

Can you try setting both `-port` and `-publicport` params (like image below)?
I think the `-port` params should work as long as it's set properly.

You can check whether you've launched the server with params by looking at `Task Manager`'s `Command Line` column in the `Processes` tab.
In case you don't see the column:
- Windows 10: right click on any column headers in the `Processes` tab and it will show a menu for you to select/deselect a column from the view.
- Windows 11: right click on any column headers in the `Processes` tab and select `Select column` in the menu. After that, pick any columns you want to show and select `OK`.
![Untitled](https://github.com/legoduded/palworld-worldoptions/assets/8759925/0346867e-38bd-466e-9d07-3036fb82be25)

**Comment by P3rf3ctXZer0** [comment]
Yes but not now. I will pin this on to list. I have a lot going on. Also when people say launch argument how do you set a launch argument not running through steam? I get my palworld from steamcmd and launch directly the ``PalServer-Win64-Test-Cmd.exe`` directly.

**Comment by Leayal** [comment]
> Yes but not now. I will pin this on to list. I have a lot going on. Also when people say launch argument how do you set a launch argument not running through steam? I get my palworld from steamcmd and launch directly the `PalServer-Win64-Test-Cmd.exe` directly.

First is that while you can launch `PalServer-Win64-Test-Cmd.exe` directly, launch the bootstrap `PalServer.exe` is much more recommended, for UE games. 

To add "launch argument", you have two ways to get it done:
- Via a shortcut file:
  1. You can right-click on the executable `.exe` file, select `Create shortcut` (In case you're on Win11, you need to `Show All Items` in the first right-click menu). A shortcut `.lnk` file will be created in the same folder of the `.exe`.
  2. After creating the shortcut, right-click on the newly created shortcut file and select `Properties`.
  3. In the `Shortcut` tab of the `Properties` dialog, you will see `Target` input box. Adding launch arguments/params by appending the said arguments to the `Target` input box. (image below). Please read both footnotes for additional information[^1][^2].
![Untitled](https://github.com/legoduded/palworld-worldoptions/assets/8759925/b4f2cca9-3283-4334-af0b-5258b1312584)
  4. After editing the shortcut's properties, select `OK` to save and close the dialog.
  5. Start the server by launching the shortcut file. And you don't need to do the 4 steps above repeatedly. Whenever you want to launch server, just launch the shortcut file, only when there's a argument needed to be changed, you can repeat starting from step 2.

- Via command-line: (you can also write a batch script, too). Please note that command's syntax has the same rule in the second footnote[^2].
  1. Start `Command-line Prompt` program (search for `cmd.exe` in the Start Menu if you don't know where it is).
  2. Enter the command `cd /d <path to the directory containing .exe>`. (E.g: `cd /d I:\Servers\palworld\server`)
  3. Enter command `PalServer.exe -port=<port number>`. (E.g: `PalServer.exe -port=6969`).
     * Alternatively, you can also use command `start "" PalServer.exe -port=<port number>`. (E.g: `start "" PalServer.exe -port=6969`), by doing this, you allow your `Command-prompt` to continue without having to wait for `PalServer.exe`'s exiting.
  6. Close the Command-prompt that is used to input commands (*NOT* the palserver's window, but the first cmd window we opened to start the server). Note: I recommend you using the `start` command in the alternative method above as you can safely close the cmd without worries in this case.

[^1]: The `Target` can contains the full path to `.exe` within double quotes `"`, if you have this case, append the launch argment *AFTER* the double quotes of the `.exe`'s path. The space to split arguments is required in any cases.
[^2]: The double quotes and the space are special characters: Arguments are separated by spaces. As long as a your one argument contains a space, they must be wrapped within the double quotes to to let Windows know that it is just one argument containing the space. This same rule applies to the `.exe` path (which leads to the note above). Notice I added a space after the `.exe` path (image above).

Happy playing, @P3rf3ctXZer0

**Comment by P3rf3ctXZer0** [comment]
This worked - thank you <3
