### ISSUE TITLE
Not sure where to start

### ISSUE THREAD

**Issue by Tom3794** [legoduded/palworld-worldoptions#2]
Hey, I'm not an expert on this, but how it works so far? I got the files but how I can change the save path? How I can run it if I'm not an expert on coding etc.

**Comment by legoduded** [comment]
I just created a compiled version which is probably exactly what you're looking for.

head over to https://github.com/legoduded/palworld-worldoptions/releases/
and download palworld-worldoptions.exe

Shutdown your server
Place your PalWorldSettings.ini into the save directory
Place palworld-worldoptions.exe into the save directory
Run palworld-worldoptions.exe
If there are no errors, go ahead and start your servers

![palworld-worldoptions](https://github.com/legoduded/palworld-worldoptions/assets/16566577/54dc8dc0-80f8-400e-8608-1de23c1f69a5)

If you get any errors, post the console output and your PalWorldSettings.ini here so I can troubleshoot

**Comment by Tom3794** [comment]
Hello Legoduded, thank you for creating this .exe file, it is very helpful, however, I think I'm doing something wrong.

Here is what I got for the OptionSettings.

![image](https://github.com/legoduded/palworld-worldoptions/assets/157782230/7081862d-77d1-48ba-9c81-df3520542759)

Maybe this is the issue? I'm trying to do everything on the folder from the local game just copying the PalWorldSettings.ini from my dedicated server. 
The only file converted was the LevelMeta.sav.

![image](https://github.com/legoduded/palworld-worldoptions/assets/157782230/8bc6d25f-1704-4023-ba6e-4cf3d832c947)

Happy to follow your instructions.

**Comment by legoduded** [comment]
Seems your PalWorldSettings.ini isn't formatted as expected.

It should look something like this:
```
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(ServerName="My Custom Server",AdminPassword="s3cure",BaseCampWorkerMaxNum=20)
```
These settings are case-sensitive.
You can post the contents of your PalWorldSettings.ini and I can try to troubleshoot more.
Or you can try the web version: [https://palworldoptions.com/](https://palworldoptions.com/)
Just input your settings and it will generate the WorldOption.sav
