### ISSUE TITLE
Please add an import the site

### ISSUE THREAD

**Issue by Mat-Hatter** [legoduded/palworld-worldoptions#21]
It would be very helpful to have an import button on the site which would allow you to upload your previous save to edit. It's inconvenient to go through every value again when you want to change a single value. Once we have configured it the first time the ini import is not a great solution as it's no longer used. You could also add and ini output to reimport later.

**Comment by legoduded** [comment]
Importing from WorldOption.sav is available on the site now. Let me know if you have any issues.
