### ISSUE TITLE
Pls add import FROM WorldOption.sav 

### ISSUE THREAD

**Issue by IMRastafari** [legoduded/palworld-worldoptions#22]
It makes no sense to make import from ini file when all my settings are in sav file and i dont have it in ini. Every time i have to reclick all stuff from zero, missing some parts and it takes so much additional time. 
Is it possibe to add import just by donwloading sav file back to sate so it takes setting from there and i can easy adjust it with couple clicks? Thank you!

**Comment by legoduded** [comment]
Importing from WorldOption.sav is available on the site now. Let me know if you have any issues.
