### ISSUE TITLE
Feature-Req:  Import config file

### ISSUE THREAD

**Issue by yoleska-dev** [legoduded/palworld-worldoptions#25]
The tool is great, but it sucks when the browser or system restarts and all the settings get reset.  Can you add a way to import the settings from a previous save?

**Comment by legoduded** [comment]
You can import from palworldsettings.ini or a worldoption.sav

![import](https://github.com/legoduded/palworld-worldoptions/assets/16566577/2cccfccc-d709-484b-8adf-83bdf4fb05ab)

hopefully, that's what you were looking for.

**Comment by yoleska-dev** [comment]
Wow, how did I miss that!.  Thanks so much!
