### ISSUE TITLE
Player List

### ISSUE THREAD

**Issue by mforbs19** [legoduded/palworld-worldoptions#26]
Since palworld added new player list to settings worldoptions.sav does not have that option yet. 

bShowPlayerList=True

**Comment by DrunkMunki** [comment]
+1 this please

**Comment by McNiel91** [comment]
Someone help we need the milk

**Comment by McNiel91** [comment]
has this been fixed or os there a similar program?

**Comment by legoduded** [comment]
sorry for the delay, I got busy this week. The website and exe have been updated with the bShowPlayerList option

**Comment by mforbs19** [comment]
Unfortunately after we implement this now you cannot purchase anything from merchants. Like you click buy and nothing happens. For whatever reason if i revert back to the old worldoptions.sav it works just fine. As soon as i import and change show player list to true and load the server back up it makes it so the merchants when you click buy nothing goes into your inventory.
