### ISSUE TITLE
Base building area

### ISSUE THREAD

**Issue by SergeyShustikov** [legoduded/palworld-worldoptions#27]
Is it possible to configure base building radius via PalWorldSettings.ini?

**Comment by Ise-Kaey** [comment]
Ther is no setting for it,
Only a (Server and Client Side) Mod. Radius will grow with ur base lvl.
https://www.nexusmods.com/palworld/mods/698

**Comment by legoduded** [comment]
as mentioned, there is no config option for building radius. You can try mods, but that's outside of the scope of what I can support.
