### ISSUE TITLE
More base mod is no longer working in latest v0.3.1 update.

### ISSUE THREAD

**Issue by Yuchenjimmy** [legoduded/palworld-worldoptions#33]
As title. I've set the max base number to 6 at base level 1, but the limit doesn't increase in game.

**Screeshots**
![Paks - 檔案總管 2024_6_27 下午 03_35_10](https://github.com/legoduded/palworld-worldoptions/assets/116278150/ec87c300-cb6b-4e1b-bda4-5071168d846a)
![Pal   2024_6_27 下午 03_35_31](https://github.com/legoduded/palworld-worldoptions/assets/116278150/9b930651-7255-4899-9928-318d131f40a1)

**Comment by el00ruobuob** [comment]
I can confirm the bug with the new version (v0.3.1.55394) as well.
Loading an advanced world (lvl 20 palbox) shows the default number of bases despite an increased basecampmod.
Existing bases seems to be working fine, even if i have over the max number of base.

edit: my zipped basecampmod file.
[basecampmod_P.zip](https://github.com/user-attachments/files/16014166/basecampmod_P.zip)

**Comment by Yuchenjimmy** [comment]
Yes, this world was just for test. Another world with base level 20, the limit is also capped to 3. But the other 10 base builded before update works fine, we just couldn't build new one.

**Comment by tazgameplays** [comment]
yes here not working also, if not fix lets agree 4 bases, is alooooooooot for 32players damn XD @legoduded help us

**Comment by Yuchenjimmy** [comment]
It turns out that we need to adjust the new option "BaseCampMaxNumInGuild" in WorldOption.sav from 4 to 128. No further steps are required.
