### ISSUE TITLE
Can I use EXE for linux server?

### ISSUE THREAD

**Issue by AnzhiZhang** [legoduded/palworld-worldoptions#5]
For convenience, can I use EXE on windows to generate file and copy to linux server? Are there any different if run this script on different platforms?

**Comment by legoduded** [comment]
yes! You can generate the WorldOptions.sav file on Windows and copy it onto a Linux server. The file generated will be the same on either platform

**Comment by AnzhiZhang** [comment]
Thanks! Could you please clarify it in the README? Sounds like linux users cannot use EXE - "If you're running a dedicated linux server you can run the tool via the scripts"
