### ISSUE TITLE
dedi

### ISSUE THREAD

**Issue by MrLucado** [legoduded/palworld-worldoptions#6]
Not an issue, but I've managed to get the PalWorldSettings.ini file to infact be read on dedicated servers.

**Comment by AnzhiZhang** [comment]
how?

**Comment by legoduded** [comment]
Most settings will read from PalWorldSettings.ini, but BaseCampWorkerMaxNum does not. The only workaround I'm aware of is using a WorldOption.sav. But if you know of another way I'm happy to hear about it.
